USE DATABASE SNOWFLAKE_SAMPLE_DATA;

DESC TABLE TPCDS_SF100TCL.STORE_SALES;

SELECT COUNT(*) FROM TPCDS_SF100TCL.STORE_SALES;

USE WAREHOUSE COMPUTE_WH;

USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS BRONZE;

CREATE OR REPLACE TABLE BRONZE.STORE_SALES_RAW AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
LIMIT 50000000;

SELECT COUNT(*) FROM BRONZE.STORE_SALES_RAW;

DESC TABLE BRONZE.STORE_SALES_RAW;

SELECT 
    COUNT(*) AS TOTAL_ROWS,
    COUNT(ss_sales_price) AS NON_NULL_SALES_PRICE
    FROM BRONZE.STORE_SALES_RAW;

SELECT MIN(ss_sold_date_sk), MAX(ss_sold_date_sk) 
FROM BRONZE.STORE_SALES_RAW;