use database SNOWFLAKE_SAMPLE_DATA;
DESC table TPCDS_SF100TCL.STORE_SALES;
SELECT COUNT(*) FROM TPCDS_SF100TCL.STORE_SALES;
use warehouse COMPUTE_WH;
use database SNOWFLAKE_LEARNING_DB;
CREATE schema IF NOT EXISTS BRONZE;
create or replace table BRONZE.STORE_SALES as
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
limit 50000000;
select * from BRONZE.STORE_SALES;