DESC TABLE SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER;

DESC TABLE SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER_ADDRESS;

USE WAREHOUSE COMPUTE_WH;

USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE OR REPLACE TABLE SILVER.CUSTOMER_DIM(
    CUSTOMER_SK NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    STATE STRING,
    START_DATE DATE,
    END_DATE DATE,
    IS_CURRENT STRING
);

INSERT INTO SILVER.CUSTOMER_DIM (CUSTOMER_ID, STATE, START_DATE, END_DATE, IS_CURRENT)
SELECT
    c.c_customer_sk,
    ca.ca_state,
    CURRENT_DATE,
    NULL,
    'Y'
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER c
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER_ADDRESS ca
    ON c.c_current_addr_sk = ca.ca_address_sk;

SELECT COUNT(*) FROM SILVER.CUSTOMER_DIM;

SELECT * FROM SILVER.CUSTOMER_DIM LIMIT 5;

CREATE OR REPLACE TABLE SILVER.CUSTOMER_STAGE AS
SELECT CUSTOMER_ID, STATE
FROM SILVER.CUSTOMER_DIM
WHERE IS_CURRENT = 'Y';

UPDATE SILVER.CUSTOMER_STAGE
SET STATE = 'TX'
WHERE CUSTOMER_ID = 48506494;

MERGE INTO SILVER.CUSTOMER_DIM AS TARGET
USING SILVER.CUSTOMER_STAGE AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
AND TARGET.IS_CURRENT = 'Y'
WHEN MATCHED AND TARGET.STATE != SOURCE.STATE THEN
    UPDATE SET 
    TARGET.END_DATE = CURRENT_DATE, 
    TARGET.IS_CURRENT = 'N'
WHEN NOT MATCHED THEN
    INSERT (CUSTOMER_ID, STATE, START_DATE, END_DATE, IS_CURRENT)
    VALUES (SOURCE.CUSTOMER_ID, SOURCE.STATE, CURRENT_DATE, NULL, 'Y');

SELECT * FROM SILVER.CUSTOMER_DIM
WHERE CUSTOMER_ID = 48506494
ORDER BY START_DATE;